### ISSUE TITLE
BUG: identical sequences cause bootstrapping to fail 

### ISSUE THREAD

**Issue by szimmerman92** [Cibiv/IQ-TREE#155] opened 2020-07-06 14:25 UTC
Hi,

I am running IQ-TREE on an alignment with 12 sequences. 9 of these sequences are apparently identical and are ignored for subsequent analysis. As a result, I am left with 3 sequences and bootstrapping seems to fail because of this. I am running version 2.0.6 on a linux operating system. I saw that this issue was fixed in version [1.5.4](http://www.iqtree.org/release/v1.5.4/) by keeping two of the identical sequences to avoid incompatibility with bootstrap and non-bootstrap runs. However, the bug still seems to be present. Below are the first several lines of the log file.

> IQ-TREE multicore version 2.0.6 for Linux 64-bit built May 30 2020
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
Host:    compute-e-16-245.o2.rc.hms.harvard.edu (AVX2, FMA3, 251 GB RAM)
Command: /home/sez10/kostic_lab/software/iqtree-2.0.6-Linux/bin/iqtree2 -s /n/scratch3/users/s/sez10/positive_selection/A_pleuropneumoniae/ete_output/OG0000310_res_filtered.fasta --prefix /n/scratch3/users/s/sez10/positive_selection/A_pleuropneumoniae/ete_output/OG0000310 -m MFP --seqtype CODON -T AUTO -B 1000
Seed:    688476 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Mon Jul  6 02:04:39 2020
Kernel:  AVX+FMA - auto-detect threads (5 CPU cores detected)
Reading alignment file /n/scratch3/users/s/sez10/positive_selection/A_pleuropneumoniae/ete_output/OG0000310_res_filtered.fasta ... Fasta format detected
Alignment most likely contains DNA/RNA sequences
Converting to codon sequences with genetic code  ...
Alignment has 12 sequences with 98 columns, 40 distinct patterns
0 parsimony-informative, 1 singleton sites, 97 constant sites

Here are the last lines of the log file with the errors

> Generating 1000 samples for ultrafast bootstrap (seed: 688476)...
ERROR: It makes no sense to perform bootstrap with less than 4 sequences.
Traceback (most recent call last):
  File "/home/sez10/.local/bin/ete3", line 11, in <module>
    load_entry_point('ete3==3.1.1', 'console_scripts', 'ete3')()
  File "/home/sez10/.local/lib/python3.6/site-packages/ete3-3.1.1-py3.6.egg/ete3/tools/ete.py", line 95, in main
    _main(sys.argv)
  File "/home/sez10/.local/lib/python3.6/site-packages/ete3-3.1.1-py3.6.egg/ete3/tools/ete.py", line 268, in _main
    args.func(args)
  File "/home/sez10/.local/lib/python3.6/site-packages/ete3-3.1.1-py3.6.egg/ete3/tools/ete_evol.py", line 852, in run
    tree = EvolTree(reformat_nw(nw), format=1)
  File "/home/sez10/.local/lib/python3.6/site-packages/ete3-3.1.1-py3.6.egg/ete3/evol/evoltree.py", line 136, in __init__
    sp_naming_function=sp_naming_function, **kwargs)
  File "/home/sez10/.local/lib/python3.6/site-packages/ete3-3.1.1-py3.6.egg/ete3/phylo/phylotree.py", line 391, in __init__
    TreeNode.__init__(self, newick=newick, format=format, **kargs)
  File "/home/sez10/.local/lib/python3.6/site-packages/ete3-3.1.1-py3.6.egg/ete3/coretype/tree.py", line 211, in __init__
    quoted_names=quoted_node_names)
  File "/home/sez10/.local/lib/python3.6/site-packages/ete3-3.1.1-py3.6.egg/ete3/parser/newick.py", line 262, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
ete3.parser.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
You may want to check other newick loading flags like 'format' or 'quoted_node_names'.

If there is anything else you need, please let me know. Thank you very much for your help.

Best,
Sam Zimmerman

**Comment by OlgaChern** [comment] 2020-07-07 08:24
Hi Sam,

in principle, if you have only three different sequences, there is no need to perform the tree search... The tree can be obtained by having a “star”-tree with three different sequences and then inserting the rest of species with identical sequences to the leaves, these sequences are identical to. If you want to have branch lengths, you can run iqtree for an alignment with three different sequences. All other branches for identical sequences are 0, i.e. you will have multifunction nodes.

Here is the example tree.
Sequences with the same colour are identical. Red branches have length 0. Black branches can be estimated from your data.



Cheers,
Olga

**Comment by OlgaChern** [comment] 2020-07-07 08:31
[ptneP6Tzy61qXZiZzH3Ivw.pdf](https://github.com/Cibiv/IQ-TREE/files/4883580/ptneP6Tzy61qXZiZzH3Ivw.pdf)

**Comment by bqminh** [comment] 2020-07-07 10:37
Thanks Olga, for the explanation!

Sam, the error message that you pasted speaks for itself:

ERROR: It makes no sense to perform bootstrap with less than 4 sequences.

It’s not a bug, so I’ll close this issue.

Minh

**Comment by szimmerman92** [comment] 2020-07-07 13:28
Hi Minh and Olga,

Thank you very much for explaining everything to me. I agree that bootstrapping is not necessary in this situation. Is there a way to make the tree Olga described above, or to run the software without bootstrapping when I run into this error in an automated fashion? My situation is that I am creating gene trees for thousands of gene families, so, I would like to be able to rerun the software automatically without bootstrapping if I run into the error.  

My current plan is to grep for the error in the standard output, if found, then rerun without bootstrapping. But I was wondering if you had any other suggestions.

Thanks so much!

Sam

**Comment by bqminh** [comment] 2020-07-08 03:49
Hi Sam, 

Your plan sounds good. Or why don't you simply discard these genes?… they don’t contribute much phylogenetic information anyway.

Alternatively, you can use -keep-ident option, so that IQ-TREE will keep identical squences in the alignment.

Minh

**Comment by szimmerman92** [comment] 2020-07-10 21:15
Sorry for the late response. I am looking for positive selection with the dn/ds ratio. I am worried that if I remove identical sequences it might bias the dn/ds ratio to have more non-synonymous mutations. Is that a valid concern?

**Comment by bqminh** [comment] 2020-07-17 03:10
No it does not matter, I think... I don't see why this might lead to such bias.

**Closed by bqminh** 2020-07-17 03:10 UTC
