### ISSUE TITLE
BUG: 1.6.10 mpi crashing with signal illegal instruction

### ISSUE THREAD

**Issue by thehamiltonlab** [Cibiv/IQ-TREE#96] opened 2019-03-12 17:53 UTC
I'm trying to run 1.6.10 (the mpi version) and I continue to get "crashes with signal illegal instruction" message.

I would love your help, if possible! Thanks.

(from output file)
************************************************
* START TREE SEARCH USING MPI WITH 1 PROCESSES *
************************************************
Random seed of master = 198329
IQ-TREE MPI multicore version 1.6.10 for Linux 64-bit built Mar 12 2019
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Host:    c8a-s1.ufhpc (AVX, FMA3, 251 GB RAM)
Command: /apps/intel/2018.1.163/openmpi/3.1.2/iq-tree/1.6.10/bin/iqtree-mpi -nt 32 -s FcC_brett_supermatrix.fas -spp FcC_supermatrix_partition.txt -m MFP+MERGE -bb 1000 -nm 5000 -bnni -alrt 1000 -bsam GENESITE -pre brett.concat.long.iqtree
Seed:    198329 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Tue Mar 12 13:28:24 2019
Kernel:  AVX+FMA - 32 threads (64 CPU cores detected)

(error)
Create initial parsimony tree by phylogenetic likelihood library (PLL)... 1.576 seconds
NOTE: ModelFinder requires 1777 MB RAM!
Testing GTR+F+G on supermatrix...
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 1   funcAbort()
ERROR: 2   ()
ERROR: 3   double PhyloTree::computeLikelihoodBranchSIMD<Vec4d, false, 4, true, false>(PhyloNeighbor*, PhyloNode*)
ERROR: 4   PhyloTree::computeLikelihood(double*)
ERROR: 5   ModelFactory::optimizeParameters(int, bool, double, double)
ERROR: 6   testOneModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Params&, Alignment*, ModelCheckpoint&, ModelInfo&, ModelsBlock*, int&, int)
ERROR: 7   testConcatModel[abi:cxx11](Params&, SuperAlignment*, ModelCheckpoint&, ModelsBlock*, int, ModelInfo&)
ERROR: 8   testPartitionModel(Params&, PhyloSuperTree*, ModelCheckpoint&, ModelsBlock*, int)
ERROR: 9   testModel(Params&, PhyloTree*, ModelCheckpoint&, ModelsBlock*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
ERROR: 10   runModelFinder(Params&, IQTree&, ModelCheckpoint&)
ERROR: 11   startTreeReconstruction(Params&, IQTree*&, ModelCheckpoint&)
ERROR: 12   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 13   main()
ERROR: 14   __libc_start_main()
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ILLEGAL INSTRUCTION
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: brett.concat.long.iqtree.log
ERROR: ***    Alignment files (if possible)
srun: error: c8a-s1: task 0: Illegal instruction (core dumped)

**Comment by bqminh** [comment] 2019-03-14 12:04
Thanks for the report, this looks strange. Does it run with non-MPI version?

**Comment by thehamiltonlab** [comment] 2019-03-14 16:37
not sure, let me test it.

**Comment by thehamiltonlab** [comment] 2019-03-14 16:59
1.6.9 works fine (as non-mpi version) on our cluster...but they did not set up 1.6.10 as non-mpi (yet...I asked them to do this so I could test).

**Comment by thehamiltonlab** [comment] 2019-03-15 16:29
update - 1.6.9 does not work fine on our cluster (a basic run works).
iqtree -s FcC_Coloradia_supermatrix2.fas -spp FcC_Coloradia_supermatrix_partition2.txt -m MFP -bb 1000 -bnni -alrt 1000  -nt 16 -pre coloradia.concat3.iqtree

This addition of this command seems to be causing the death...at the same place, over and over (see output below)
-bsam GENESITE

UPDATE BEST LOG-LIKELIHOOD: -425591.897
Iteration 210 / LogL: -425592.688 / Time: 1h:11m:44s (0h:9m:57s left)
Iteration 220 / LogL: -425693.914 / Time: 1h:14m:42s (0h:6m:28s left)
Iteration 230 / LogL: -425614.676 / Time: 1h:17m:35s (0h:3m:2s left)
Iteration 240 / LogL: -425599.812 / Time: 1h:20m:22s (0h:0m:-21s left)
Refining ufboot trees with NNI 5 branches...
100 samples done
ERROR: alignment.cpp:70: std::__cxx11::string &Alignment::getSeqName(int): Assertion `i >= 0 && i < (int)seq_names.size()' failed.
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: coloradia.concat3.iqtree.log
ERROR: ***    Alignment files (if possible)
/tmp/slurmd/job33554941/slurm_script: line 18: 12687 Aborted                 (core dumped) iqtree -s FcC_Coloradia_supermatrix2.fas -spp FcC_Coloradia_supermatrix_partition2.txt -m MFP -bb 1000 -bnni -alrt 1000 -bsam GENESITE -nt 16 -pre coloradia.concat3.iqtree

**Comment by bqminh** [comment] 2019-03-25 13:33
I believe this is caused by the combination of -bnni with -bsam GENESITE option. These two options are simply not working peacefully with each other...

**Comment by thehamiltonlab** [comment] 2019-03-25 15:52
Thanks for looking into this!

**Comment by bqminh** [comment] 2019-06-03 12:50
Should be fixed in v1.6.11

**Closed by bqminh** 2019-06-03 12:50 UTC

**Comment by bqminh** [comment] 2020-05-29 05:49
We have found and fixed this bug. For the time being please add option `-keep_empty_seq` whenever you use -bsam GENESITE or -bsam GENE option.
Thanks
